const J={app:"キキトリ",voice:"話して入力",stop:"停止する",busy:"清書中",polish:"選んだモードで清書",done:"清書しました。",diary:"日記",minutes:"議事録",summary:"要約",copy:"コピー",copied:"コピー済み",save:"保存しました。",restore:"直前の内容を復元しました。"};
const storageKey="kikitori.entries.v4",undoKey="kikitori.undo.v4";
const modeHelp={diary:"出来事と気持ちを、読みやすい日記として清書します。AI連携時は自然な文章に整えます。",minutes:"会議の文字起こしを、議題・要点・決定事項・課題に整理します。AI連携が必要です。",summary:"長い文章から重要点だけを短くまとめます。AI連携が必要です。"};
const el={date:document.querySelector("#entryDate"),record:document.querySelector("#recordButton"),recordLabel:document.querySelector("#recordLabel"),status:document.querySelector("#speechStatus"),raw:document.querySelector("#rawText"),out:document.querySelector("#diaryText"),polish:document.querySelector("#polishButton"),loading:document.querySelector("#polishLoading"),save:document.querySelector("#saveButton"),clear:document.querySelector("#clearButton"),restore:document.querySelector("#restoreButton"),copy:document.querySelector("#copyButton"),image:document.querySelector("#imageButton"),pdf:document.querySelector("#pdfButton"),word:document.querySelector("#wordButton"),history:document.querySelector("#historyList"),count:document.querySelector("#entryCount"),modeHelp:document.querySelector("#modeHelp"),audioFile:document.querySelector("#audioFile"),audioStatus:document.querySelector("#audioStatus"),install:document.querySelector("#installHelpButton"),dialog:document.querySelector("#installDialog"),closeDialog:document.querySelector("#closeDialogButton")};
let currentMode="diary",recognition=null,isRecording=false;const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function today(){const n=new Date(),l=new Date(n.getTime()-n.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)}
function formatDate(v){if(!v)return"";const p=v.split("-").map(Number);return p[0]+"年"+p[1]+"月"+p[2]+"日"}
function setStatus(m){el.status.textContent=m}
function setAudioStatus(m,type){if(!el.audioStatus)return;el.audioStatus.textContent=m||"";el.audioStatus.classList.toggle("is-busy",type==="busy");el.audioStatus.classList.toggle("is-error",type==="error")}
function entries(){try{return JSON.parse(localStorage.getItem(storageKey))||[]}catch{return[]}}
function saveEntries(a){localStorage.setItem(storageKey,JSON.stringify(a))}
function escapeHtml(t){return t.replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function normalizeLocalText(t){return t.replace(/\r/g,"").replace(/[ \t　]+/g," ").replace(/えっと|えーと|あのー|まあその|なんか/g,"").replace(/([。！？]){2,}/g,"$1").trim()}
function simpleDiary(raw,date){const text=normalizeLocalText(raw);if(!text)return"";const sentences=text.replace(/([。！？])/g,"$1\n").split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>/[。！？]$/.test(x)?x:x+"。");return formatDate(date)+"の日記\n\n"+sentences.join("\n\n")}
async function requestAiPolish(payload){const r=await fetch("/api/polish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"AI清書を実行できませんでした。");if(!data.text||typeof data.text!=="string")throw new Error("AIから清書結果を受け取れませんでした。");return data.text.trim()}
async function polish(){const raw=el.raw.value.trim();if(!raw){setStatus("先に元の内容を入力してください。");el.raw.focus();return}el.polish.disabled=true;el.polish.classList.add("is-busy");el.polish.textContent=J.busy;el.loading.hidden=false;setStatus("AIに清書を依頼しています。長い文章では少し時間がかかります。");try{el.out.value=await requestAiPolish({mode:currentMode,text:raw,date:el.date.value||today()});setStatus(J.done)}catch(e){if(currentMode==="diary"){el.out.value=simpleDiary(raw,el.date.value||today());setStatus("AI連携に失敗したため、日記を簡易清書しました。理由: "+(e.message||"不明なエラー"))}else{el.out.value="";setStatus("AI連携に失敗しました。理由: "+(e.message||"不明なエラー"))}console.info(e)}finally{el.loading.hidden=true;el.polish.disabled=false;el.polish.classList.remove("is-busy");el.polish.textContent=J.polish;document.querySelector(".draft-panel").scrollIntoView({behavior:"smooth",block:"start"})}}
function renderHistory(){const a=entries().sort((x,y)=>y.updatedAt.localeCompare(x.updatedAt));el.count.textContent=a.length+"件";el.history.innerHTML="";if(!a.length){const p=document.createElement("p");p.className="history-preview";p.textContent="保存するとここに並びます。";el.history.append(p);return}a.forEach(e=>{const item=document.createElement("article");item.className="history-item";const b=document.createElement("button");b.type="button";b.innerHTML='<div class="history-date">'+formatDate(e.date)+'・'+(e.modeLabel||'')+'</div><p class="history-preview">'+escapeHtml(e.output.slice(0,90))+(e.output.length>90?'...':'')+'</p>';b.onclick=()=>{el.date.value=e.date;el.raw.value=e.raw;el.out.value=e.output;setStatus("保存した内容を開きました。")};item.append(b);el.history.append(item)})}
function setupSpeech(){if(!SpeechRecognition){setStatus("このブラウザでは音声認識ボタンが使えない場合があります。入力欄に直接書くこともできます。");el.record.onclick=()=>{el.raw.focus();setStatus("入力欄を開きました。")};return}recognition=new SpeechRecognition();recognition.lang="ja-JP";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let f="",i="";for(let x=e.resultIndex;x<e.results.length;x++){const t=e.results[x][0].transcript;if(e.results[x].isFinal)f+=t;else i+=t}if(f)el.raw.value+=(el.raw.value.trim()?"\n":"")+f;setStatus(i?"聞き取り中："+i:"聞き取り中です。")};recognition.onend=()=>{isRecording=false;el.record.classList.remove("is-recording");el.recordLabel.textContent=J.voice;setStatus("聞き取りを止めました。")};recognition.onerror=()=>{isRecording=false;el.record.classList.remove("is-recording");el.recordLabel.textContent=J.voice;setStatus("音声入力を開始できませんでした。SafariやChromeでお試しください。")};el.record.onclick=()=>{if(isRecording){recognition.stop();return}isRecording=true;el.record.classList.add("is-recording");el.recordLabel.textContent=J.stop;setStatus("聞き取り中です。");recognition.start()}}
async function transcribeAudioFile(file){if(!file){setAudioStatus("ファイルが選択されませんでした。","error");return}setAudioStatus("選択: "+file.name+" / "+Math.ceil(file.size/1024/1024)+"MB","busy");const max=25*1024*1024;if(file.size>max){const msg="音声ファイルが25MBを超えています。分割または圧縮してから試してください。";setStatus(msg);setAudioStatus(msg,"error");return}const allowed=/\.(mp3|mp4|mpeg|mpga|m4a|wav|webm|ogg|flac)$/i;if(!allowed.test(file.name)){const msg="対応形式は mp3, m4a, wav, webm などの音声ファイルです。";setStatus(msg);setAudioStatus(msg,"error");return}const fd=new FormData();fd.append("audio",file);setStatus("録音ファイルを文字起こし中です。長い音声では時間がかかります。");setAudioStatus("文字起こし中です。画面を閉じずにお待ちください。","busy");try{const r=await fetch("/api/transcribe",{method:"POST",body:fd});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"文字起こしできませんでした。");const text=(data.text||"").trim();if(!text)throw new Error("文字起こし結果が空でした。");el.raw.value+=(el.raw.value.trim()?"\n":"")+text;setStatus("録音ファイルの文字起こしが完了しました。");setAudioStatus("文字起こし完了: "+file.name,"")}catch(e){const msg="録音ファイルの文字起こしに失敗しました。理由: "+(e.message||"不明なエラー");setStatus(msg);setAudioStatus(msg,"error")}finally{el.audioFile.value=""}}

function getOutput(){const t=el.out.value.trim();if(!t)setStatus("先に清書してください。");return t}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function baseName(){return"kikitori-"+(el.date.value||today())}
function exportWord(){const t=getOutput();if(!t)return;const h='<html><head><meta charset="utf-8"></head><body><pre style="font-family:sans-serif;white-space:pre-wrap;line-height:1.7">'+escapeHtml(t)+'</pre></body></html>';download(new Blob([h],{type:"application/msword"}),baseName()+".doc");setStatus("Wordファイルを書き出しました。")}
function exportPdf(){const t=getOutput();if(!t)return;const w=window.open("","_blank");w.document.write('<pre style="font-family:sans-serif;white-space:pre-wrap;line-height:1.7">'+escapeHtml(t)+'</pre>');w.document.close();w.print();setStatus("PDFは印刷画面から保存できます。")}
function wrapCanvasText(ctx,text,maxWidth){const out=[];text.split("\n").forEach(paragraph=>{if(!paragraph.trim()){out.push("");return}let line="";for(const ch of paragraph){const next=line+ch;if(ctx.measureText(next).width>maxWidth&&line){out.push(line);line=ch}else{line=next}}if(line)out.push(line)});return out}
function drawA4Page(lines,pageIndex,totalPages){const c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=1240;c.height=1754;ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle="#d9e5e1";ctx.lineWidth=2;ctx.strokeRect(48,48,c.width-96,c.height-96);ctx.fillStyle="#0f766e";ctx.font="bold 42px sans-serif";ctx.fillText(J.app,90,108);ctx.fillStyle="#64716f";ctx.font="24px sans-serif";ctx.fillText((el.date.value||today())+"  "+pageIndex+"/"+totalPages,90,148);ctx.fillStyle="#15211f";ctx.font="30px sans-serif";let y=210;for(const line of lines){if(line){ctx.fillText(line,90,y)}y+=42}return c}
function exportImage(){const t=getOutput();if(!t)return;const scratch=document.createElement("canvas").getContext("2d");scratch.font="30px sans-serif";const wrapped=wrapCanvasText(scratch,t,1060);const firstLimit=36,otherLimit=38;const pages=[];let index=0;while(index<wrapped.length){const limit=pages.length?otherLimit:firstLimit;pages.push(wrapped.slice(index,index+limit));index+=limit}if(!pages.length)pages.push([]);pages.forEach((lines,i)=>{const canvas=drawA4Page(lines,i+1,pages.length);canvas.toBlob(blob=>{setTimeout(()=>download(blob,baseName()+"-a4-"+(i+1)+".png"),i*250)},"image/png")});setStatus(pages.length===1?"A4縦の画像を書き出しました。":"A4縦の画像を"+pages.length+"ページに分けて書き出しました。")}
document.querySelectorAll(".mode-button").forEach(button=>{button.onclick=()=>{currentMode=button.dataset.mode;document.querySelectorAll(".mode-button").forEach(target=>target.classList.toggle("is-active",target===button));el.modeHelp.textContent=modeHelp[currentMode]}});
el.polish.onclick=polish;el.save.onclick=()=>{const output=el.out.value.trim();if(!output){setStatus("先に清書してください。");return}const labels={diary:J.diary,minutes:J.minutes,summary:J.summary};const a=entries();a.push({date:el.date.value||today(),raw:el.raw.value,output,mode:currentMode,modeLabel:labels[currentMode],updatedAt:new Date().toISOString()});saveEntries(a);renderHistory();setStatus(J.save)};
el.clear.onclick=()=>{const s={date:el.date.value,raw:el.raw.value,output:el.out.value};if(s.raw.trim()||s.output.trim())localStorage.setItem(undoKey,JSON.stringify(s));el.raw.value="";el.out.value="";el.date.value=today();setStatus("新しく書けます。直前の内容は元に戻せます。")};
el.restore.onclick=()=>{const saved=localStorage.getItem(undoKey);if(!saved){setStatus("復元できる内容がありません。");return}const s=JSON.parse(saved);el.date.value=s.date||today();el.raw.value=s.raw||"";el.out.value=s.output||"";setStatus(J.restore)};
el.copy.onclick=async()=>{const t=getOutput();if(!t)return;try{await navigator.clipboard.writeText(t)}catch{el.out.focus();el.out.select();document.execCommand("copy")}el.copy.textContent=J.copied;setTimeout(()=>{el.copy.textContent=J.copy},1400)};
el.audioFile.addEventListener("change",()=>transcribeAudioFile(el.audioFile.files&&el.audioFile.files[0]));el.image.onclick=exportImage;el.pdf.onclick=exportPdf;el.word.onclick=exportWord;el.install.onclick=()=>el.dialog.showModal();el.closeDialog.onclick=()=>el.dialog.close();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=17").catch(()=>{});el.date.value=today();el.modeHelp.textContent=modeHelp[currentMode];setStatus("話した内容、または文字起こしを入れてください。");setupSpeech();renderHistory();
